name: protfolio
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  # sdk: ">=2.19.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  # google_fonts: ^3.0.1
  shared_preferences: ^2.0.15
  animated_text_kit: ^4.2.2
  font_awesome_flutter: ^10.4.0
  flutter_svg: ^1.1.6
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.0
  fluttertoast: ^8.2.12
  # url_launcher_web: ^2.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/logo/
    - assets/icons/
    - assets/images/
    - assets/images/projects/pelican/
    - assets/images/projects/oceanicview/
    - assets/images/projects/litsports/
    - assets/images/projects/thrillpay/


  fonts:
    - family: Agustina
      fonts:
        - asset: fonts/agustina/agustina.otf

    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/montserrat.ttf

    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-Light.ttf
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 900
        - asset: fonts/poppins/Poppins-Medium.ttf
          weight: 300
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 500
        - asset: fonts/poppins/Poppins-Italic.ttf
          style: italic

